# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Munchers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_ENV: production
      COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
      COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      NEXT_PUBLIC_ENV: production
      COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
      COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38F6FCFACCDA4FB29E82C0E9E3BEDC7B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4FC4D5E8A3E84BAD8E53CC3F6C892BFC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20EB5D86AACB4303A728CF2ED52EBD69 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Munchers'
          slot-name: 'Production'
          package: .
